modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "moretnts"
version = "${file.jarVersion}"
displayName = "MoreTNTs"
authors = "MrStupsi"
description = '''
This mod adds more tnts into Minecraft
'''

[[dependencies.moretnts]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moretnts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"